services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seriesdb
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d seriesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: lab6-web-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: seriesdb
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger/"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    image: lab6-web-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy